### ISSUE TITLE
bug in yara b64-regexp-generator

### ISSUE THREAD

**Issue by Bill-ColeUS** [InQuest/python-inquestlabs#4]
Hello,

I am interested to create some regexp for detecting executables in MIME attachments. I tried your generator and found a small bug (or feature?).

When I try to generate a regexp for `.scr`, it actually generates a rule that matches `scr` only, for some reason the dot is not matched.

Here is an example with your web API, from: https://labs.inquest.net/tools/yara/b64-regexp-generator

```
curl  "https://labs.inquest.net/api/yara/base64re?option=none&instring=.scr"
Result
([\x2b\x2f-9A-Za-z][3HXn]Njc[g-v]|[\x2b\x2f-9A-Za-z]{4}c2Ny|[\x2b\x2f-9A-Za-z]{2}[159BFJNRVZdhlptx]zY3[I-L])
```

matches the MIME attachment:

```
Content-Disposition: attachment; filename="=?UTF-8?B?aXNjcml6aW9uZWNhbXBp?=
```

As you will notice, my curl request is for `.scr` but the generated regexp matches `scr` at the start of the filename, something it should not have done.

Thank you.

**Comment by pedramamini** [comment]
@Bill-ColeUS we completely missed this issue creation, apologies. Assigning it for answer now.

**Comment by deadpixi** [comment]
Hello @Bill-ColeUS,
Thank you for checking out the b64re tool!

I think what's happening is that, in `.scr`, the generator is seeing the `.` as the regular expression "match any" character. You can escape the dot by using a backslash, or by enclosing it in square brackets. For example:

    curl  "https://labs.inquest.net/api/yara/base64re?option=none&instring=%5B.%5Dscr"

This produces:

    ([\x2b\x2f-9A-Za-z][CSiy]5zY3[I-L]|LnNjc[g-v]|[\x2b\x2f-9A-Za-z]{2}[048AEIMQUYcgkosw]uc2Ny)

Which seems to work better.

However, be warned that there is a bit of "fuzziness" when matching Base64-encoded stuff, due to the way the encoding works. Bits from one byte can be mixed into the preceding or following byte at the beginning or end of the string depending on how things are lined up. In general, and especially for short patterns, the expression will be fuzzy around the edges by necessity.

Hope this helps!

**Comment by Bill-ColeUS** [comment]
Then lets call it a documentation bug :)

I'll try with the dot escaped and see how that goes.

Thank you!
